# Generated by Django 5.1.2 on 2024-10-25 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCat', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloConEs', models.CharField(max_length=200)),
                ('fechaConEs', models.DateTimeField(auto_now_add=True)),
                ('descripcionConEs', models.TextField()),
                ('enlaceConEs', models.URLField(blank=True, null=True)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenConIm', models.ImageField(upload_to='consulta_imagenes/')),
                ('consultaEstatica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='consultas.consultaestatica')),
            ],
        ),
    ]
