# Generated by Django 5.1.2 on 2024-10-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consultaestatica',
            name='categoriaFK',
        ),
        migrations.RemoveField(
            model_name='consultaimagen',
            name='consultaEstatica',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='ConsultaEstatica',
        ),
        migrations.DeleteModel(
            name='ConsultaImagen',
        ),
    ]
