# Generated by Django 5.1.2 on 2024-10-27 16:15

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Categoria = apps.get_model('consultas', 'Categoria')
    categorias = ["Salud", "Educacion", "Noticias", "Educacion"]
    for nombre in categorias:
        Categoria.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):
    dependencies = [
        ('consultas', '0003_categoria_consulta_categoria'), 
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
