# Generated by Django 5.1.2 on 2024-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
